### ISSUE TITLE
Stops working after ~1 week.

### ISSUE THREAD

**Issue by Crypto2** [fioprotocol/fiostore#1]
After about a week requests start returning the error "An invalid request was sent in, please check the nested errors for details.:" and it has to be restarted.

**Comment by Crypto2** [comment]
Sometimes it stops working as soon as a couple of hours of running. Not sure if anyone watches these issues?

**Comment by blockpane** [comment]
Do the app logs show the file and line number where it's failing? This is most likely fee drift and should be pretty easy to fix, but want to make sure I'm looking in the right place.

**Comment by Crypto2** [comment]
Next time it does it I'll see if it says, I don't *think* it did though.
